name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  tag:
    needs: [build]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
      with:
        prefix: v
    
    - name: Use the version
      run: |
        echo ${{ steps.version.outputs.version }}
    - name: Use the previous version
      run: |
        echo ${{ steps.version.outputs.previous-version }}
    
  run_terraform:
    needs: [tag]
    uses: cleannetcode/CleannetCode_bot/.github/workflows/terraform.yml@master
