name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  tag:
    needs: [build]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        
    - name: Display GitVersion variables (with prefix)
      run: |
        echo "Major: ${{ env.GitVersion_Major }}"
        echo "Minor: ${{ env.GitVersion_Minor }}"
        echo "Patch: ${{ env.GitVersion_Patch }}"
        echo "PreReleaseTag: ${{ env.GitVersion_PreReleaseTag }}"
        echo "PreReleaseTagWithDash: ${{ env.GitVersion_PreReleaseTagWithDash }}"
        echo "PreReleaseLabel: ${{ env.GitVersion_PreReleaseLabel }}"
        echo "PreReleaseNumber: ${{ env.GitVersion_PreReleaseNumber }}"
        echo "WeightedPreReleaseNumber: ${{ env.GitVersion_WeightedPreReleaseNumber }}"
        echo "BuildMetaData: ${{ env.GitVersion_BuildMetaData }}"
        echo "BuildMetaDataPadded: ${{ env.GitVersion_BuildMetaDataPadded }}"
        echo "FullBuildMetaData: ${{ env.GitVersion_FullBuildMetaData }}"
        echo "MajorMinorPatch: ${{ env.GitVersion_MajorMinorPatch }}"
        echo "SemVer: ${{ env.GitVersion_SemVer }}"
        echo "LegacySemVer: ${{ env.GitVersion_LegacySemVer }}"
        echo "LegacySemVerPadded: ${{ env.GitVersion_LegacySemVerPadded }}"
        echo "AssemblySemVer: ${{ env.GitVersion_AssemblySemVer }}"
        echo "AssemblySemFileVer: ${{ env.GitVersion_AssemblySemFileVer }}"
        echo "FullSemVer: ${{ env.GitVersion_FullSemVer }}"
        echo "InformationalVersion: ${{ env.GitVersion_InformationalVersion }}"
        echo "BranchName: ${{ env.GitVersion_BranchName }}"
        echo "EscapedBranchName: ${{ env.GitVersion_EscapedBranchName }}"
        echo "Sha: ${{ env.GitVersion_Sha }}"
        echo "ShortSha: ${{ env.GitVersion_ShortSha }}"
        echo "NuGetVersionV2: ${{ env.GitVersion_NuGetVersionV2 }}"
        echo "NuGetVersion: ${{ env.GitVersion_NuGetVersion }}"
        echo "NuGetPreReleaseTagV2: ${{ env.GitVersion_NuGetPreReleaseTagV2 }}"
        echo "NuGetPreReleaseTag: ${{ env.GitVersion_NuGetPreReleaseTag }}"
        echo "VersionSourceSha: ${{ env.GitVersion_VersionSourceSha }}"
        echo "CommitsSinceVersionSource: ${{ env.GitVersion_CommitsSinceVersionSource }}"
        echo "CommitsSinceVersionSourcePadded: ${{ env.GitVersion_CommitsSinceVersionSourcePadded }}"
        echo "UncommittedChanges: ${{ env.GitVersion_UncommittedChanges }}"
        echo "CommitDate: ${{ env.GitVersion_CommitDate }}"
    
  run_terraform:
    needs: [tag]
    uses: cleannetcode/CleannetCode_bot/.github/workflows/terraform.yml@master
